.github/workflows/ci.yml
build.gradle

sonarcloud 분석 등록했습니다
<br>
close #6
<br>

feat: sonarcloud 등록

---

src/main/java/postman/bottler/user/controller/UserService.java
src/main/java/postman/bottler/user/service/UserService.java

유저 서비스 인터페이스 추가했습니다.
- 유저 블락
- 프로필 이미지 요청
<br>
resolves #7 
<br>

 Feature/#7 user 유저 서비스 인터페이스 추가

---

src/main/java/postman/bottler/notification/controller/NotificationService.java
src/main/java/postman/bottler/notification/service/NotificationService.java

타 도메인이 요청하는 기능을 우선적으로 인터페이스에 추가하였습니다.
- 키워드 편지 도착 알림
- 받은 사용자 ID
- 해당 편지 ID
- 타겟 편지 알림
- 받은 사용자 ID
- 해당 편지 ID
- 답장 편지 알림
- 받은 사용자 ID
- 해당 편지 ID
- 사용자 경고 알림
- 경고 받은 사용자 ID
- 사용자 정지 알림
- 정지 받은 사용자 ID
<br>
resolves: #7
<br>

feat: `Notification` 서비스 인터페이스 외부 요청 기능 추가

---

src/main/java/postman/bottler/mapletter/controller/MapLetterController.java
src/main/java/postman/bottler/mapletter/controller/MapLetterService.java
src/main/java/postman/bottler/mapletter/service/MapLetterService.java

map letter 편지 블락 메서드 추가
<br>
#7 
<br>

[Feature/#7] map letter 편지 블락 메서드 추가

---

.github/workflows/ci-cd.yml

hotfix: ci-cd 변경

---

.github/workflows/ci-cd.yml

hotfix: cd 수정

---

.github/workflows/ci-cd.yml

hotfix: ci-cd 수정
<br>
close #32 
<br>

hotfix: ci-cd 수정

---

.github/workflows/ci-cd.yml

hotfix: cd sudo 제거

---

src/main/java/postman/bottler/BottlerApplication.java
src/main/java/postman/bottler/scheduler/SchedulerConfig.java

추후 스케쥴러 기능 구현을 위해 구현해야 할 기능을 작성하여 주석처리 하였습니다.
2개 이상의 도메인이 작업하게 될 것 같아, Config를 미리 작성하였습니다.
- 추천 키워드 편지 보내기
- 정지 기한 지난 유저 해제
close #53 
<br>

Feature/#53 스케쥴러 config 등록 및 구현해야 할 기능 작성

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/mapletter/controller/MapLetterController.java

지도 편지 userDetails 붙이기
<br>
close #{이슈넘버}
<br>

fix: #72 지도 편지 userDetails 붙이기

---

src/main/java/postman/bottler/label/controller/LabelController.java
src/main/java/postman/bottler/label/domain/Label.java
src/main/java/postman/bottler/label/dto/LabelResponseDTO.java
src/main/java/postman/bottler/label/dto/request/LabelRequestDTO.java
src/main/java/postman/bottler/label/service/LabelService.java
src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
src/main/java/postman/bottler/user/service/UserRepository.java
src/main/java/postman/bottler/user/service/UserService.java
src/test/java/postman/bottler/label/domain/LabelTest.java
src/test/java/postman/bottler/label/service/LabelServiceTest.java

- 라벨 CustomUserDetails 도입
<br>
#{72}
<br>

fix: #72 라벨 userDetails

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/user/controller/UserController.java

- 유저 CustomUserDetails 도입
<br>
#{72}
<br>

fix: #72 유저 userDetails

---

src/main/java/postman/bottler/complaint/controller/ComplaintController.java
src/main/java/postman/bottler/complaint/dto/request/ComplaintRequestDTO.java
src/main/java/postman/bottler/notification/controller/NotificationController.java
src/main/java/postman/bottler/notification/dto/request/SubscriptionRequestDTO.java
src/main/java/postman/bottler/notification/dto/request/UserNotificationRequestDTO.java

신고 및 알림 도메인 JWT 구현에 따른 코드 수정
ref #72
<br>

[fix#72]: `신고`, `알림` 도메인 CustomUserDetails 적용으로 인한 수정

---

src/main/java/postman/bottler/letter/controller/LetterBoxController.java
src/main/java/postman/bottler/letter/controller/LetterController.java
src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
src/main/java/postman/bottler/letter/service/DeleteManagerService.java
src/main/java/postman/bottler/letter/service/LetterBoxService.java
src/main/java/postman/bottler/letter/service/LetterService.java
src/main/java/postman/bottler/letter/service/ReplyLetterService.java

키워드 편지 userDetails 적용<br>
close #72
<br>

fix: 키워드 편지 userDetails 적용

---

.github/workflows/cd.yml
build.gradle

swagger 버전 충돌 해결<br>
close #79
<br>

hotfix: swagger gradle 버전 충돌 해결

---

src/main/java/postman/bottler/config/SecurityConfig.java

- cors 설정 추가
<br>
close #{82}
<br>

feat: cors 설정 추가

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/user/auth/JwtAccessDeniedHandler.java
src/main/java/postman/bottler/user/auth/JwtAuthenticationEntryPoint.java
src/main/java/postman/bottler/user/infra/UserJpaRepository.java
src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
src/main/java/postman/bottler/user/service/UserRepository.java
src/main/java/postman/bottler/user/service/UserService.java

- 유저 닉네임으로 id 받아오는 메서드 추가
<br>
<br>

feat: 유저 닉네임으로 id 받아오는 메서드 추가

---

build.gradle
src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/mapletter/dto/FindReceivedMapLetterDTO.java
src/main/java/postman/bottler/mapletter/dto/FindSentMapLetter.java
src/main/java/postman/bottler/mapletter/dto/response/FindNearbyLettersResponseDTO.java
src/main/java/postman/bottler/mapletter/infra/MapLetterJpaRepository.java
src/main/java/postman/bottler/mapletter/service/MapLetterService.java

유저 닉네임, 프로필 가져오도록 수정(합치기)
<br>
close #{이슈넘버}
<br>

fix: #101 유저 닉네임, 프로필 가져오도록 수정(합치기)

---

src/main/java/postman/bottler/user/infra/UserRepositoryImpl.java
src/main/java/postman/bottler/user/service/BanService.java
src/main/java/postman/bottler/user/service/UserRepository.java
src/main/java/postman/bottler/user/service/UserService.java

fix: 트랜잭션 설정 추가

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/user/auth/JwtFilter.java

- security config 설정 추가
<br>
<br>

refactor: security config 설정 추가

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/global/HealthCheckController.java

feat: healthcheck 추가

---

src/main/java/postman/bottler/config/SecurityConfig.java

fix: #141 도메인 허용 변경

---

src/main/java/postman/bottler/user/dto/response/UserResponseDTO.java

- 유저 정보 조회 response 변경 
<br>
close #118 
<br>

refactor: 유저 정보 조회 response 변경

---

src/main/java/postman/bottler/mapletter/dto/response/OneLetterResponseDTO.java
src/main/java/postman/bottler/mapletter/dto/response/OneReplyLetterResponseDTO.java
src/main/java/postman/bottler/mapletter/service/MapLetterService.java

로그인 한 유저가 해당 편지의 주인인지 확인하는 로직 추가
<br>
close #136 
<br>

fix: #136 로그인 한 유저가 해당 편지의 주인인지 확인하는 로직 추가

---

.github/workflows/cd.yml
docker-compose/docker-compose.yml

redis 배포 환경 설정 추가
<br>
redis 배포 환경 설정 추가
close #117 
<br>

feat: redis 배포 환경 설정 추가

---

src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
src/main/java/postman/bottler/scheduler/SchedulerConfig.java

키워드 편지 추천 스케쥴러 로직 추가
close #148 
<br>

[Refactor/#148] 키워드 편지 추천 스케쥴러 로직 추가

---

src/main/java/postman/bottler/user/controller/AuthController.java
src/main/java/postman/bottler/user/controller/OAuthController.java
src/main/java/postman/bottler/user/dto/response/SignInDTO.java
src/main/java/postman/bottler/user/dto/response/SignInResponseDTO.java
src/main/java/postman/bottler/user/service/UserService.java

- 리프레시 토큰 쿠키로 반환
<br>
close #152 
<br>

refactor: 리프레시 토큰 쿠키로 반환

---

src/main/java/postman/bottler/user/controller/AuthController.java

- 리프레시 토큰 유효성 검사 시 쿠키에서 가져오도록 수정
<br>
close #152 
<br>

refactor: 리프레시 토큰 유효성 검사 시 쿠키에서 가져오도록 수정

---

src/main/java/postman/bottler/user/auth/CookieService.java
src/main/java/postman/bottler/user/controller/AuthController.java
src/main/java/postman/bottler/user/controller/OAuthController.java
src/main/resources/application.yml

- 리프레시 토큰 쿠키 sameSite 설정 추가
<br>
close #152 
<br>

Feature/#152 리프레시 토큰 쿠키 sameSite 설정 추가

---

src/main/java/postman/bottler/user/auth/JwtTokenProvider.java
src/main/java/postman/bottler/user/service/UserService.java

- 새로 발급한 액세스 토큰 권한 문제 해결
<br>
close #152 
<br>

fix: 새로 발급한 토큰 권한 문제 해결

---

src/test/java/postman/bottler/complaint/domain/ComplaintsTest.java
src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
src/test/java/postman/bottler/complaint/service/ComplaintServiceTest.java
src/test/resources/application.yml

신고 리팩토링으로 인한 테스트 코드 컴파일 오류를 수정하였습니다.
close #171 
<br>

fix: 신고 테스트 코드 컴파일 오류 수정

---

src/main/resources/application.yml

- 액세스 토큰 유효 시간 변경
<br>
close #152 
<br>

refactor: 액세스 토큰 유효 시간 변경

---

src/main/java/postman/bottler/config/SecurityConfig.java
src/main/java/postman/bottler/scheduler/SchedulerConfig.java

정지 유저 편지 작성 제한
close #189 
<br>

refactor: 정지 유저 접근 권한 제한

---

src/main/java/postman/bottler/BottlerApplication.java
src/main/java/postman/bottler/user/infra/entity/EmailCodeEntity.java

develop to main

---

src/main/java/postman/bottler/user/infra/entity/EmailCodeEntity.java

fix: 이메일 인증 유효시간 수정

---

src/main/java/postman/bottler/user/controller/UserController.java
src/main/java/postman/bottler/user/domain/EmailCode.java
src/main/java/postman/bottler/user/infra/EmailCodeJpaRepository.java
src/main/java/postman/bottler/user/infra/EmailCodeRepositoryImpl.java
src/main/java/postman/bottler/user/service/EmailCodeRepository.java
src/main/java/postman/bottler/user/service/UserService.java

fix: 이메일 인증 후 인증코드 삭제

---

src/main/java/postman/bottler/letter/controller/ReplyLetterController.java
src/main/java/postman/bottler/letter/dto/response/ReplyLetterDetailResponseDTO.java
src/main/java/postman/bottler/letter/infra/ReplyLetterJpaRepository.java
src/main/java/postman/bottler/letter/infra/ReplyLetterRepositoryImpl.java
src/main/java/postman/bottler/letter/service/ReplyLetterRepository.java
src/main/java/postman/bottler/letter/service/ReplyLetterService.java

isReplied 키워드 답장 편지 상세에 추가<br>
close #208 
<br>

feat: isReplied 키워드 답장 편지 상세에 추가

---

src/main/java/postman/bottler/mapletter/service/MapLetterService.java

타겟 편지 생성 시, 알림 예외 수정
close #211 
<br>

hotfix: 저장된 편지의 ID가 들어가도록 수정

---

src/main/java/postman/bottler/letter/infra/entity/LetterEntity.java
src/main/java/postman/bottler/letter/infra/entity/ReplyLetterEntity.java
src/main/java/postman/bottler/mapletter/infra/entity/MapLetterEntity.java
src/main/java/postman/bottler/mapletter/infra/entity/ReplyMapLetterEntity.java

편지 JPA Entity content TEXT 타입으로 수정
close #214 
<br>

refactor: JPA Entity 편지 content text 타입으로 수정

---

src/main/java/postman/bottler/keyword/service/RedisLetterService.java
src/main/java/postman/bottler/scheduler/RecommendationScheduler.java

편지 추천 검증 조건 변경<br>
close #216 
<br>

fix: 편지 추천 검증 조건 변경

---

src/main/java/postman/bottler/keyword/controller/RecommendationController.java

키워드 편지 테스트 api 구현<br>
close #219 
<br>

feat: 키워드 편지 테스트 api 구현

---

src/main/resources/application.yml

hotfix: hikari 설정 추가

---

src/main/java/postman/bottler/complaint/application/repository/ComplaintRepository.java
src/main/java/postman/bottler/complaint/application/repository/KeywordComplaintRepository.java
src/main/java/postman/bottler/complaint/application/repository/KeywordReplyComplaintRepository.java
src/main/java/postman/bottler/complaint/application/repository/MapComplaintRepository.java
src/main/java/postman/bottler/complaint/application/repository/MapReplyComplaintRepository.java
src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
src/main/java/postman/bottler/complaint/infra/keyword/KeywordComplaintRepositoryImpl.java
src/main/java/postman/bottler/complaint/infra/keyword/KeywordReplyComplaintRepositoryImpl.java
src/main/java/postman/bottler/complaint/infra/map/MapComplaintRepositoryImpl.java
src/main/java/postman/bottler/complaint/infra/map/MapReplyComplaintRepositoryImpl.java
src/main/java/postman/bottler/complaint/presentation/ComplaintController.java
src/main/java/postman/bottler/complaint/service/ComplaintService.java
src/main/java/postman/bottler/letter/service/ReplyLetterService.java
src/main/java/postman/bottler/mapletter/service/MapLetterService.java
src/main/java/postman/bottler/notification/application/PushNotificationProvider.java
src/main/java/postman/bottler/notification/application/repository/NotificationRepository.java
src/main/java/postman/bottler/notification/application/repository/SubscriptionRepository.java
src/main/java/postman/bottler/notification/application/service/NotificationService.java
src/main/java/postman/bottler/notification/application/service/SubscriptionService.java
src/main/java/postman/bottler/notification/infra/FirebasePushProvider.java
src/main/java/postman/bottler/notification/infra/RedisNotificationRepositoryImpl.java
src/main/java/postman/bottler/notification/infra/SubscriptionRepositoryImpl.java
src/main/java/postman/bottler/notification/presentation/NotificationController.java
src/main/java/postman/bottler/scheduler/RecommendationScheduler.java
src/main/java/postman/bottler/user/service/UserService.java
src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
src/test/java/postman/bottler/complaint/infra/MapComplaintRepositoryTest.java
src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
src/test/java/postman/bottler/notification/application/SubscriptionServiceTest.java

알림과 신고 도메인의 패키지 구조를 변경하였습니다.
- controller => presentation
- service => application
ref #227

Chore/#227 알림/신고 패키지 구조 변경

---

src/main/java/postman/bottler/mapletter/exception/MapLetterExceptionHandler.java

지도 편지 에러 리팩토링
<br>
close #{이슈넘버}
<br>

refactor: #242 지도 편지 에러 리팩토링

---

src/main/java/postman/bottler/complaint/exception/ComplaintExceptionHandler.java
src/main/java/postman/bottler/notification/exception/NotificationExceptionHandler.java

Refactor/#242 : 알림/신고 예외 코드 응답 수정

---

src/main/java/postman/bottler/label/exception/LabelExceptionHandler.java
src/main/java/postman/bottler/user/exception/UserExceptionHandler.java

- 유저, 라벨 ResponseStatus 수정
<br>
close #{이슈넘버}
<br>

refactor: 유저, 라벨 ResponseStatus 수정

---

src/main/java/postman/bottler/notification/application/dto/response/NotificationResponseDTO.java
src/main/java/postman/bottler/notification/application/service/NotificationService.java
src/main/java/postman/bottler/notification/domain/LetterNotification.java
src/main/java/postman/bottler/notification/domain/Notification.java
src/main/java/postman/bottler/notification/domain/Notifications.java
src/main/java/postman/bottler/notification/domain/Subscriptions.java
src/test/java/postman/bottler/notification/application/NotificationServiceTest.java
src/test/java/postman/bottler/notification/domain/NotificationTest.java
src/test/java/postman/bottler/notification/domain/NotificationTypeTest.java
src/test/java/postman/bottler/notification/domain/NotificationsTest.java
src/test/java/postman/bottler/notification/domain/SubscriptionTest.java
src/test/java/postman/bottler/notification/domain/SubscriptionsTest.java
src/test/java/postman/bottler/notification/infra/FirebaseMessageMapperTest.java
src/test/java/postman/bottler/notification/infra/SubscriptionRepositoryImplTest.java

알림 도메인 테스트 코드를 추가하였습니다.
close #228 
<br>

Test/#228 알림 테스트 코드 추가

---

src/main/java/postman/bottler/complaint/application/service/ComplaintService.java
src/main/java/postman/bottler/complaint/domain/Complaint.java
src/main/java/postman/bottler/complaint/domain/Complaints.java
src/test/java/postman/bottler/complaint/application/ComplaintServiceTest.java
src/test/java/postman/bottler/complaint/domain/ComplaintTest.java
src/test/java/postman/bottler/complaint/domain/ComplaintsTest.java
src/test/java/postman/bottler/complaint/infra/KeywordComplaintRepositoryTest.java
src/test/java/postman/bottler/complaint/infra/KeywordReplyComplaintRepositoryImplTest.java
src/test/java/postman/bottler/complaint/infra/MapReplyComplaintRepositoryImplTest.java
src/test/java/postman/bottler/complaint/infra/entity/KeywordComplaintEntityTest.java
src/test/java/postman/bottler/complaint/infra/entity/KeywordReplyComplaintEntityTest.java
src/test/java/postman/bottler/complaint/infra/entity/MapComplaintEntityTest.java
src/test/java/postman/bottler/complaint/infra/entity/MapReplyComplaintEntityTest.java

신고 도메인 테스트를 추가하였습니다.
close #237 
<br>

Test/#237 신고 테스트 추가

---

build.gradle
src/main/java/postman/bottler/config/SecurityConfig.java
src/main/resources/application.yml

actuator와 프로메테우스 설정을 추가하였습니다.
close #254 
<br>

Chore/#254 actuator 모니터링 설정 추가

---

docker-compose/docker-compose.yml

chore: 모니터링 포트 추가

---

.github/workflows/cd.yml

chore: yml base64 디코딩 추가

---

.github/workflows/cd.yml
.github/workflows/ci.yml

ci-cd: develop to main

---

src/main/java/postman/bottler/complaint/application/service/ComplaintService.java

refactor: 추상화 수준 리팩토링

---

.github/workflows/cd.yml
build.gradle
docker-compose/docker-compose.yml

로그 관련 설정을 수정 및 추가하였습니다.
- 로그 시간대 서울로 변경
- 로그 파일로 관리하도록 설정 추가
close #291 
<br>

Chore : 로그 설정 수정

---

src/main/java/postman/bottler/complaint/application/service/ComplaintService.java

빌드 오류 수정 중, 사라진 메서드 내용을 복구하였습니다.
close #{이슈넘버}
<br>

fix: 메서드 변경 내용 복구
